name: Java CI with Gradle 1.20.1

on:
  push:
    branches: [ "1.20.1" ]
  pull_request:
    branches: [ "1.20.1" ]

jobs:
  compile:
    name: Gradle compiler
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Java 21 setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-package: jdk
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: gradle build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/ReTerraForged/ReTerraForged/target/
